version: "3.9"
services:
  anexos_mongo_transparencia:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    image: registry.gitlab.alverad.com.br/anexos/anexos_api:latest
    environment:
      - TZ=America/Belem
    env_file:
      - .env
    restart: always
    networks:
      - traefik-public
    volumes:
      - type: bind
        source: /var/log/apiAnexoMongo.log
        target: /apiAnexoMongo.log
    ports:
      - ${APP_PORT}:${APP_PORT}

networks:
  traefik-public:
    external: true
